title: Dokumentasi Sistem Penyelenggaraan Pemilihan OSIS
default_lang: id
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'

